### ISSUE TITLE
[Request] Add TMOHentai icons

### ISSUE THREAD

**Issue by edgarMejia** [as280093/TIcons#2]
Web: https://tmohentai.com/

**Comment by as280093** [comment]
Here 
https://github.com/as280093/TIcons/tree/master/Requested%20Extensions%20Icons/tmohentai.com/res
![web_hi_res_512](https://user-images.githubusercontent.com/25240839/57439813-6f3bd900-7264-11e9-9af8-2f9735ab1f4c.png)
